baseURL = 'https://quetoo.org/'
languageCode = 'en-us'
title = 'Quetoo'
theme = 'quetoo'

[services]
  [services.googleAnalytics]
    ID = 'G-071NWTJCT1'

[params]
  description = 'A free first person shooter for Mac, PC and Linux'
  discord = 'https://discord.gg/unb9U4b'
  github = 'https://github.com/jdolan/quetoo'
  releases = 'https://github.com/jdolan/quetoo/releases'
  sponsor = 'https://github.com/sponsors/jdolan'
  youtube = 'https://youtube.com/@WickedOldGames'
  itch = 'https://wickedoldgames.itch.io/quetoo'
  facebook = 'https://www.facebook.com/@Quetoo.org'
  cssVersion = "2"
  taglines = [
    "Pwning nubz, one rail slug at a time.",
    "Bringing 2006 graphics to 1996 in 2026.",
    "I love the smell of giblets in the morning."
  ]

[menu]
  [[menu.main]]
    name = 'News'
    url = '/news/'
    weight = 1
  [[menu.main]]
    name = 'Media'
    url = '/media/'
    weight = 2
  [[menu.main]]
    name = 'Downloads'
    url = '/downloads/'
    weight = 3
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 4
  [[menu.main]]
    name = 'Community'
    url = '/community/'
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
